# Generated by Django 3.0.3 on 2020-03-20 04:09

import creditcards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200320_0409'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cartProduct',
        ),
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='address_details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visa',
            name='card_expiry',
            field=creditcards.models.CardExpiryField(null=True, verbose_name='expiration date'),
        ),
        migrations.AddField(
            model_name='visa',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25, null=True, verbose_name='card number'),
        ),
        migrations.AddField(
            model_name='visa',
            name='card_owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visa',
            name='cvv',
            field=creditcards.models.SecurityCodeField(max_length=4, null=True, verbose_name='security code'),
        ),
    ]
