# Generated by Django 3.0.3 on 2020-03-17 18:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(blank=True, editable='true', max_length=11)),
                ('gender', models.CharField(default='F', max_length=20)),
                ('birthDate', models.DateField(default=datetime.date.today)),
                ('address1', models.TextField(blank=True, editable='true', max_length=100)),
                ('address2', models.TextField(blank=True, editable='true', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_img', verbose_name='image')),
                ('creditNumber', models.CharField(blank=True, editable='true', max_length=19)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
