# Generated by Django 3.0.3 on 2020-03-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200317_1805'),
        ('products', '0009_remove_sub_category_sub_cat_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='1', max_length=255)),
                ('addingDate', models.DateField(auto_now=True)),
                ('cartProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('cartUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
