# Generated by Django 3.0.3 on 2020-03-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='addingDate',
            field=models.DateField(auto_now=True),
        ),
    ]
