# Generated by Django 3.0.3 on 2020-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='addingDate',
            field=models.DateField(auto_now=True),
        ),
    ]
