# Generated by Django 3.0.3 on 2020-03-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='addingDate',
        ),
    ]
