# Generated by Django 3.0.3 on 2020-03-20 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200317_1805'),
        ('cart', '0005_auto_20200319_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
