# Generated by Django 3.0.3 on 2020-03-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comments_favourite_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='user_imgs'),
        ),
    ]
