# Generated by Django 3.0.3 on 2020-03-08 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200308_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
