# Generated by Django 3.0.3 on 2020-03-09 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200308_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
