# Generated by Django 3.0.4 on 2020-03-14 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address1',
            field=models.TextField(blank=True, editable='true', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.TextField(blank=True, editable='true', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='profile',
            name='creditNumber',
            field=models.CharField(blank=True, editable='true', max_length=19),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='F', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, editable='true', max_length=11),
        ),
    ]
