# Generated by Django 3.0.3 on 2020-03-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='empty.jpg', upload_to='product_imgs'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='empty.jpg', upload_to='product_imgs'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='empty.jpg', upload_to='product_imgs'),
        ),
    ]
