# Generated by Django 3.0.3 on 2020-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200307_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='empty.jpg', upload_to='cat_imgs'),
        ),
    ]
