# Generated by Django 3.0.3 on 2020-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_cat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_img',
        ),
        migrations.AddField(
            model_name='sub_category',
            name='sub_cat_img',
            field=models.ImageField(default='empty.jpg', upload_to='subcat_imgs'),
        ),
    ]
