# Generated by Django 3.0.3 on 2020-03-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200308_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_ratedby',
        ),
    ]
