# Generated by Django 3.0.3 on 2020-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200309_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='product_imgs/empty.png', upload_to='product_imgs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='product_imgs/empty.png', upload_to='product_imgs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='product_imgs/empty.png', upload_to='product_imgs'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_img',
            field=models.ImageField(default='subcat_imgs/empty.jpg', upload_to='subcat_imgs'),
        ),
    ]
