# Generated by Django 3.0.3 on 2020-03-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_sub_category_sub_cat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.TextField(null=True),
        ),
    ]
