# Generated by Django 3.0.3 on 2020-03-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
