# Generated by Django 3.0.3 on 2020-03-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200319_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
