# Generated by Django 3.0.3 on 2020-03-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.CharField(blank=True, max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
